package:
  format-version: "1.0.0"
  name: "wireless_pic32cxbz_wbz"
  type: "package"
  status: "production"
  required: false
  version: "v1.4.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.19.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v11.1.0"
    - name: "core"
      type: "package"
      version: "v3.13.4"
    - name: "crypto"
      type: "package"
      version: "v3.8.1"
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "bsp"
      type: "package"
      version: "v3.20.0"
