package:
  format-version: "1.0.0"
  name: "wireless_pic32cxbz_wbz"
  type: "package"
  status: "production"
  required: false
  version: "v1.4.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.19.1"
    - name: "core"
      type: "package"
      version: "v3.13.5"
    - name: "crypto"
      type: "package"
      version: "v3.8.1"
    - name: "bsp"
      type: "package"
      version: "v3.20.1"
